spring.application.name=spring-cicd-demo
server.port=8080

# Expose actuator endpoints (handy for K8s health/liveness probes later)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
